spring:
  redis:
    host: 10.200.131.78
    port: 6379
    password: open123wlg
    database: 9
  datasource:
    url: jdbc:mysql://10.200.131.78:3306/purchase?characterEncoding=utf8&serverTimezone=UTC&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useAffectedRows=true
    username: root
    password: 20170104lws

mapper:
  mappers: org.trc.scm.core.mybatis.BaseMapper
  not-empty: true
  identity: MYSQL
  style: camelhump
  safeDelete: true
  safeUpdate: true

mybatis:
  type-aliases-package: org.trc.scm.purchase.model.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true